version: '3.8'

services:
  app:
    container_name: my_app
    build: .
    environment:
      DB: "host=db user=postgres password=postgres dbname=postgres sslmode=disable"
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}
